[[manager.prepend_keymap]]
on   = [ "s" ]
run  = "plugin keyjump"
desc = "Keyjump (Normal mode)"

[[manager.prepend_keymap]]
on   = [ "<ENTER>" ]
run  = "plugin smart-enter"
desc = "Enter the directory, or open the file"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank" ]

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"
